// ploaness lints itself with the rules it publishes.
//
// The shipped `ploaness/eslint` cannot be used verbatim here: every one of its scoped blocks globs a
// Payload layout (`src/**`, `tests/int`, the generated mount), and this repository is a pnpm workspace
// of five packages. So the framework-neutral half is imported from `@ploaness/config/eslint-core` and
// composed against this layout. No rule is restated - only the globs differ, which is the one part that
// is genuinely repository-shaped.
import {
  baseLayers,
  compose,
  guidelineRules,
  immutabilityBlock,
  prettierLast,
  processConfigBlock,
  testIdiomRules,
  testIntegrityRules,
  testSuiteSyntaxRules,
  typeAwareParsing,
  vitestPlugin,
} from '@ploaness/config/eslint-core'

const SOURCE = 'packages/*/src/**/*.ts'
const SPECS = 'packages/*/test/**/*.spec.ts'
// The programs that implement a check - the fixture mutations, the asset-body staging helper, the two
// package build scripts - need no glob of their own any more. They are TypeScript now, node strips
// their types where it runs them, and `tsconfig.lint.json` names them so the type-aware pass has a
// project to read them in. The unscoped rule block below therefore reaches them like anything else.

export default compose(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'coverage/**',
      'dist-tarballs/**',
      // Fixture sources, which are deliberate counterexamples. The programs that mutate them are not:
      // they are checks this repository implements, and they are linted through CHECK_PROGRAMS below.
      'it/project/**',
      'it/**/node_modules/**',
      // Verbatim payload bodies, not source: generated copies of files that live at the repo root.
      'packages/assets/files/**',
      // Generated by packages/ploaness/build.mjs from the shipped configs.
      'packages/ploaness/biome.json',
      'packages/ploaness/tsconfig.json',
      // Ambient declarations for the re-export shims. They carry no statements to lint, and putting
      // them in a project only to satisfy the parser would compile a consumer's entry points here.
      '**/*.d.ts',
      // Nothing hand-written in this repository is JavaScript any more: the analyzer configs and the
      // package entry shims are TypeScript sources that compile into the `dist` trees already ignored
      // above, and the check programs are TypeScript that node type-strips where it runs them. What is
      // left matching these globs is build output and this file, whose loader reads it as JavaScript.
      '**/*.js',
      '**/*.mjs',
    ],
  },

  ...baseLayers,

  // Not `projectService: true`: this repository's root tsconfig is a solution file (`files: []` plus
  // references), which the project service handles poorly. The explicit project is the honest binding.
  typeAwareParsing({ project: ['./tsconfig.lint.json'], tsconfigRootDir: import.meta.dirname }),
  { rules: guidelineRules },

  // The network guard is the one exemption, and it is a role rather than a convenience: installing a
  // guard on `net.Socket.prototype` and on the DNS resolvers IS mutation of an existing object, so the
  // rule has nothing to propose there. Every other module in this repository is held to it. The
  // exemption names one path rather than a directory, so a second file in `packages/config/src` does not
  // inherit it by sitting next door.
  immutabilityBlock([SOURCE, SPECS], ['packages/config/src/vitest-setup.ts']),

  // This repository's own root setup file, held to the same role the shipped configs give a consumer's.
  // It needs no environment today; carrying the block is what stops the three configs drifting again.
  processConfigBlock(),

  {
    files: [SPECS],
    plugins: { vitest: vitestPlugin },
    rules: {
      // The test-integrity block the shipped config applies to a Payload project's suite. This
      // repository publishes those rules and was not measured by them, which is the whole reason
      // eslint-core.js exists.
      ...testIntegrityRules,
      // Both tables whole, rather than the selectors spliced and the exemptions listed by hand. Splicing
      // them here was correct and still drifted: this block named three of the five idiom rules the
      // shipped configs name, so this repository's own specs were held to two rules it publishes an
      // exemption from. A third hand-written copy of a policy drifts exactly as the second one did.
      ...testIdiomRules,
      // Spread WHOLE, because this key REPLACES the base setting rather than adding to it. Naming a
      // subset here silently disarms the rest - the trap `eslint-core.js` documents, which this block
      // fell into once already with the inheritance ban.
      ...testSuiteSyntaxRules,
    },
  },

  prettierLast,
)
