// ploaness lints itself with the rules it publishes.
//
// The shipped `ploaness/eslint` cannot be used verbatim here: every one of its scoped blocks globs a
// Payload layout (`src/**`, `tests/int`, the generated mount), and this repository is a pnpm workspace
// of five packages. So the framework-neutral half is imported from `@ploaness/config/eslint-core` and
// composed against this layout. No rule is restated - only the globs differ, which is the one part that
// is genuinely repository-shaped.
import {
  baseLayers,
  compose,
  guidelineRules,
  immutabilityBlock,
  NO_FAST_CHECK_SEED,
  NO_INHERITANCE,
  NO_LITERAL_ASSERTIONS,
  NO_NETWORK_GUARD_ESCAPE,
  NO_TEST_ORDER_ESCAPE,
  prettierLast,
  testIntegrityRules,
  typeAwareParsing,
  vitestPlugin,
} from '@ploaness/config/eslint-core'

const SOURCE = 'packages/*/src/**/*.ts'
const SPECS = 'packages/*/test/**/*.spec.ts'
// The programs that implement a check - the fixture mutations, the asset-body staging helper, the two
// package build scripts - need no glob of their own any more. They are TypeScript now, node strips
// their types where it runs them, and `tsconfig.lint.json` names them so the type-aware pass has a
// project to read them in. The unscoped rule block below therefore reaches them like anything else.

export default compose(
  {
    ignores: [
      '**/dist/**',
      '**/node_modules/**',
      'coverage/**',
      'dist-tarballs/**',
      // Fixture sources, which are deliberate counterexamples. The programs that mutate them are not:
      // they are checks this repository implements, and they are linted through CHECK_PROGRAMS below.
      'it/project/**',
      'it/**/node_modules/**',
      // Verbatim payload bodies, not source: generated copies of files that live at the repo root.
      'packages/assets/files/**',
      // Generated by packages/ploaness/build.mjs from the shipped configs.
      'packages/ploaness/biome.json',
      'packages/ploaness/tsconfig.json',
      // Ambient declarations for the re-export shims. They carry no statements to lint, and putting
      // them in a project only to satisfy the parser would compile a consumer's entry points here.
      '**/*.d.ts',
      // Nothing hand-written in this repository is JavaScript any more: the analyzer configs and the
      // package entry shims are TypeScript sources that compile into the `dist` trees already ignored
      // above, and the check programs are TypeScript that node type-strips where it runs them. What is
      // left matching these globs is build output and this file, whose loader reads it as JavaScript.
      '**/*.js',
      '**/*.mjs',
    ],
  },

  ...baseLayers,

  // Not `projectService: true`: this repository's root tsconfig is a solution file (`files: []` plus
  // references), which the project service handles poorly. The explicit project is the honest binding.
  typeAwareParsing({ project: ['./tsconfig.lint.json'], tsconfigRootDir: import.meta.dirname }),
  { rules: guidelineRules },

  // The network guard is the one exemption, and it is a role rather than a convenience: installing a
  // guard on `net.Socket.prototype` and on the DNS resolvers IS mutation of an existing object, so the
  // rule has nothing to propose there. Every other module in this repository is held to it. The
  // exemption names one path rather than a directory, so a second file in `packages/config/src` does not
  // inherit it by sitting next door.
  immutabilityBlock([SOURCE, SPECS], ['packages/config/src/vitest-setup.ts']),

  {
    files: [SPECS],
    plugins: { vitest: vitestPlugin },
    rules: {
      // The test-integrity block the shipped config applies to a Payload project's suite. This
      // repository publishes those rules and was not measured by them, which is the whole reason
      // eslint-core.js exists.
      ...testIntegrityRules,
      // The literal-assertion ban, which the shipped config applies to a Payload project's tests.
      // `NO_INHERITANCE` is spread in beside it because this key REPLACES the base setting rather than
      // adding to it, so naming only the assertion selectors here silently disarmed the inheritance ban
      // in every spec - the exact trap `eslint-core.js` documents.
      'no-restricted-syntax': [
        ...NO_INHERITANCE,
        ...NO_LITERAL_ASSERTIONS,
        ...NO_FAST_CHECK_SEED,
        ...NO_TEST_ORDER_ESCAPE,
        ...NO_NETWORK_GUARD_ESCAPE,
      ],
      // A test's expected value IS its specification. Naming it moves the specification away from the
      // assertion that reads it, which makes the test harder to check by eye rather than easier - the
      // opposite of what the bare-number ban exists to achieve. This is a role distinction, not a
      // convenience: production code names its constants, and a spec states its literals.
      '@typescript-eslint/no-magic-numbers': 'off',
      // Fixture data repeats by nature; naming each occurrence is noise rather than clarity.
      'sonarjs/no-duplicate-string': 'off',
      // Specs assemble tokens from fragments so a rule under test does not match its own spec.
      'unicorn/numeric-separators-style': 'off',
    },
  },

  prettierLast,
)
