// Compare generated bytes before and after regeneration; verification reports drift rather than accepting a repair.

/** One generated artefact, as the gate saw it either side of regenerating. */
export interface RegeneratedArtefact {
  /** The repo-relative path the generator owns. */
  readonly target: string
  /** Whether git tracks the path, so that what the generator produced is reviewable. */
  readonly isTracked: boolean
  /** The bytes on disk before the generator ran, or undefined when there were none. */
  readonly before: string | undefined
  /** The bytes on disk after it ran, or undefined when the configuration produces no such artefact. */
  readonly after: string | undefined
}

const driftOf = (artefact: RegeneratedArtefact): readonly string[] => {
  // An artefact the configuration does not produce is not this gate's business. A project with no admin
  // panel has no import map, and demanding one would be a rule about the shape of the project.
  if (artefact.after === undefined) {
    return []
  }
  // Asked before drift, because "it drifted" is a strange thing to say about a file git has never seen.
  // An untracked artefact regenerates from a configuration nobody can review, which is a worse fault
  // than drift rather than a milder one.
  if (!artefact.isTracked) {
    return [
      `${artefact.target} is not tracked by git, so no committed version exists to compare against`,
    ]
  }
  return artefact.before === artefact.after ? [] : [`${artefact.target} changed when regenerated`]
}

/**
 * Report every generated artefact that regeneration changed, or that git does not track.
 * @param artefacts each generated path, with the bytes either side of running its generator.
 * @returns one message per artefact that drifted or is untracked, in the order given.
 */
export const findGeneratedDrift = (artefacts: readonly RegeneratedArtefact[]): readonly string[] =>
  artefacts.flatMap((artefact: RegeneratedArtefact): readonly string[] => driftOf(artefact))
