// The secret allowlist.
//
// The standard requires a repository to list every fake credential it commits as a test fixture, and
// requires the secret scan to fail on anything outside that list. Until now there was no way to satisfy
// both: `.gitleaks.toml` is a forbidden managed path, precisely so a project cannot weaken the scanner's
// own rules, and no setting replaced it. A project with a fixture credential could not pass at all.
//
// The resolution keeps the file forbidden and makes the allowlist data instead. ploaness renders the
// scanner's configuration itself, outside the working tree, from entries the project declares. The
// rendered config always extends the tool's default rules, so a declared entry can only add a named
// exception and can never replace or disable what the scanner already looks for.

/** One committed fake credential, and the reason it is committed. */
export interface SecretException {
  /** A repo-relative path whose findings are excused. */
  readonly path: string
  readonly reason: string
}

const escapeForRegex = (value: string): string =>
  value.replaceAll(/[.*+?^${}()|[\]\\]/g, String.raw`\$&`)

const escapeForToml = (value: string): string =>
  value.replaceAll('\\', '\\\\').replaceAll('"', String.raw`\"`)

/**
 * Render a scanner configuration from the declared exceptions.
 * @param exceptions the recorded exceptions.
 * @returns TOML that extends the scanner's default rules and adds one allowlist per exception.
 */
export const renderGitleaksConfig = (exceptions: readonly SecretException[]): string => {
  const header: string = [
    '# Generated by ploaness. Do not commit this file: a copy in the working tree could only shadow or',
    '# weaken the rules ploaness supplies, which is why the path is forbidden.',
    '[extend]',
    'useDefault = true',
    '',
  ].join('\n')
  const blocks: readonly string[] = exceptions.map((exception: SecretException): string =>
    [
      '[[allowlists]]',
      `description = "${escapeForToml(exception.reason)}"`,
      `paths = ['''^${escapeForRegex(exception.path)}$''']`,
      '',
    ].join('\n'),
  )
  return [header, ...blocks].join('\n')
}
