// Judge a real generated inventory against independently chosen fixture package coordinates and bytes.
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { asRecord, isArray, readKey } from '@ploaness/governance'
import { invoke, requireResult } from './browser-server-support.js'

const EXECUTABLE_ARGUMENT: number = 2
const executable: string | undefined = process.argv[EXECUTABLE_ARGUMENT]
if (executable === undefined) {
  throw new Error('Expected the packed ploaness executable')
}
const bom: Record<string, unknown> = asRecord(JSON.parse(readFileSync('dist/sbom/bom.cdx.json', 'utf8')))
const metadata: Record<string, unknown> = asRecord(JSON.parse(readFileSync('dist/sbom/release.json', 'utf8')))
const components: unknown = bom['components']
const graph: unknown = bom['dependencies']
if (!(isArray(components) && isArray(graph))) {
  throw new Error('The SBOM has no component inventory or dependency graph')
}
for (const [name, version] of [
  ['is-odd', '3.0.1'],
  ['is-number', '6.0.0'],
  ['is-number', '7.0.0'],
] as const) {
  if (
    !components.some(
      (entry: unknown): boolean => readKey(entry, 'name') === name && readKey(entry, 'version') === version,
    )
  ) {
    throw new Error(`The SBOM omitted ${name}@${version}`)
  }
}
const hasEdge = (parent: string, child: string): boolean =>
  graph.some((edge: unknown): boolean => {
    const children: unknown = readKey(edge, 'dependsOn')
    return readKey(edge, 'ref') === parent && isArray(children) && children.includes(child)
  })
for (const member of ['one', 'two']) {
  if (!hasEdge(`pkg:npm/sbom-${member}@1.0.0`, 'pkg:npm/is-odd@3.0.1')) {
    throw new Error(`The SBOM lost the shared dependency of workspace ${member}`)
  }
}
if (!hasEdge('pkg:npm/is-odd@3.0.1', 'pkg:npm/is-number@6.0.0')) {
  throw new Error('The SBOM lost the transitive dependency relationship')
}
const hashFile = (file: string): string => createHash('sha256').update(readFileSync(file)).digest('hex')
if (metadata['sbomSha256'] !== hashFile('dist/sbom/bom.cdx.json') || metadata['sourceDirty'] !== false) {
  throw new Error('The SBOM release metadata does not describe the fixture and generated bytes')
}
const artifacts: unknown = metadata['artifacts']
if (!isArray(artifacts) || readKey(artifacts[0], 'sha256') !== hashFile('dist/release.tgz')) {
  throw new Error('The release archive was not measured')
}
const manifestFile: string = 'packages/one/package.json'
const original: string = readFileSync(manifestFile, 'utf8')
try {
  writeFileSync(manifestFile, original.replace('"3.0.1"', '"3.0.0"'))
  requireResult(await invoke(executable, ['sbom', '--artifact', 'dist/release.tgz']), 1, 'frozen lockfile specifier')
} finally {
  writeFileSync(manifestFile, original)
}
requireResult(
  await invoke(executable, ['sbom', '--artifact', 'dist/release.tgz', '--output', 'authored-inventory']),
  1,
  'ignored artifact directory',
)
console.info('SBOM workspace identities, relationships, artifacts and failure contracts passed')
