import { describe, expect, it } from 'vitest'
import { type AgentReferenceMatch, findAgentReferences } from '../src/agent-references.js'

describe('findAgentReferences', () => {
  it('returns no matches for a plain commit message', () => {
    expect(findAgentReferences('feat(x): add a real feature\n\nBecause it was needed.')).toEqual([])
  })

  it('does not flag a bare product name used in prose', () => {
    // This repository ships agent instructions and documents such tools by name, so a legitimate
    // documentation commit that mentions an agent must pass.
    expect(findAgentReferences('docs: explain the claude code skill loading order')).toEqual([])
    expect(findAgentReferences('feat: add cursor support to the editor pane')).toEqual([])
  })

  it('flags a Co-Authored-By trailer naming an agent, case-insensitively', () => {
    const matches: readonly AgentReferenceMatch[] = findAgentReferences(
      'fix: something\n\nCo-Authored-By: Claude <x@y.com>',
    )
    expect(matches).toEqual([{ line: 3, label: 'agent co-authorship trailer' }])
  })

  it('flags a co-author trailer for other known agents', () => {
    for (const agent of ['Copilot', 'Cursor', 'Codex', 'Devin', 'Aider']) {
      expect(
        findAgentReferences(`Co-authored-by: ${agent} <bot@example.com>`).map(
          (match) => match.label,
        ),
      ).toContain('agent co-authorship trailer')
    }
  })
})

describe('a signature or identifier that names an agent', () => {
  it('flags an agent vendor sign-off email', () => {
    expect(
      findAgentReferences('Co-authored-by: A B <noreply@anthropic.com>').length,
    ).toBeGreaterThan(0)
    expect(findAgentReferences('signed by assistant@openai.com')[0]?.label).toBe(
      'agent vendor email',
    )
  })

  it('flags an agent session identifier', () => {
    expect(findAgentReferences('chore: tidy\n\nClaude-Session: abc-123')).toEqual([
      { line: 3, label: 'agent session identifier' },
    ])
    expect(findAgentReferences('Codex-Session-Id: 42')[0]?.label).toBe('agent session identifier')
    expect(findAgentReferences('Agent Session: 7')[0]?.label).toBe('agent session identifier')
  })

  it('flags a generated-by signature', () => {
    expect(findAgentReferences('Generated with Claude Code')[0]?.label).toBe(
      'agent generation signature',
    )
    expect(findAgentReferences('Generated by GPT-4o')[0]?.label).toBe('agent generation signature')
  })

  it('flags the robot-emoji generated-with signature line', () => {
    const line: string = `${String.fromCodePoint(0x1f916)} Generated with Claude Code`
    expect(findAgentReferences(line)[0]?.label).toBe('agent generation signature')
  })

  it('flags the Claude Code product signature link', () => {
    expect(findAgentReferences('See [Claude Code](https://claude.com/claude-code)')[0]?.label).toBe(
      'agent product signature',
    )
  })

  it('reports the 1-based line of each match', () => {
    const matches: readonly AgentReferenceMatch[] = findAgentReferences(
      'feat: x\nbody\nCo-authored-by: Cursor <a@b.com>',
    )
    expect(matches[0]?.line).toBe(3)
  })
})
