import { describe, expect, it } from 'vitest'
import {
  type DeclaredExclusion,
  findConvenienceExclusions,
  findUnreachedExclusions,
  readSettings,
  type Settings,
} from '../src/settings.js'

const entry = (overrides: Partial<DeclaredExclusion> = {}): DeclaredExclusion => ({
  setting: 'coverageExclude',
  pattern: 'src/generated/**',
  reason: 'generated by the framework, so there is no hand-written logic to measure',
  kind: 'glob',
  ...overrides,
})

const MEASURED: readonly string[] = ['src/generated/types.ts', 'src/lib/token.ts']

describe('findConvenienceExclusions', () => {
  it('accepts an exclusion that states the role it claims', () => {
    expect(findConvenienceExclusions([entry()])).toEqual([])
  })

  it('reports an exclusion that states no reason', () => {
    const found: readonly string[] = findConvenienceExclusions([entry({ reason: '' })])
    expect(found[0]).toContain('states no reason')
  })

  // The standard once forbade naming an individual file and now judges an exclusion by what it reaches
  // instead. A named file the report measured excludes something, so it is no longer a finding here.
  it('accepts a pattern that names one file the report measured', () => {
    const single: DeclaredExclusion = entry({ pattern: 'src/lib/token.ts' })
    expect(findConvenienceExclusions([single])).toEqual([])
  })

  it('judges every entry, so one good exclusion cannot hide a bad one', () => {
    const entries: readonly DeclaredExclusion[] = [entry(), entry({ reason: '' })]
    expect(findConvenienceExclusions(entries)).toHaveLength(1)
  })

  it('still requires a route prefix to state why the crawl skips it', () => {
    const route: DeclaredExclusion = entry({
      setting: 'accessibilitySkipRoutes',
      pattern: '/media',
      reason: '',
      kind: 'route',
    })
    expect(findConvenienceExclusions([route])[0]).toContain('states no reason')
  })
})

describe('findUnreachedExclusions', () => {
  it('accepts a glob that matches a file the report measured', () => {
    expect(findUnreachedExclusions([entry()], MEASURED)).toEqual([])
  })

  it('reports a glob that matches nothing the report measured', () => {
    const stale: DeclaredExclusion = entry({ pattern: 'src/legacy/**' })
    expect(findUnreachedExclusions([stale], MEASURED)[0]).toContain('excludes nothing')
  })

  it('reports a named file the report never measured', () => {
    const renamed: DeclaredExclusion = entry({ pattern: 'src/lib/gone.ts' })
    expect(findUnreachedExclusions([renamed], MEASURED)[0]).toContain('excludes nothing')
  })

  // `**\/` crosses a directory boundary and `*` does not. Reading the two alike would let
  // `src/*.ts` claim to reach a file nested three levels down, and pass an exclusion that excludes it.
  it('does not let a single star cross a directory boundary', () => {
    const shallow: DeclaredExclusion = entry({ pattern: 'src/*.ts' })
    expect(findUnreachedExclusions([shallow], MEASURED)[0]).toContain('excludes nothing')
  })

  it('reads a typography exclusion as the regular expression that setting carries', () => {
    const typography: DeclaredExclusion = entry({
      setting: 'typographyExclusions',
      pattern: '^src/generated/',
      kind: 'regex',
    })
    expect(findUnreachedExclusions([typography], MEASURED)).toEqual([])
  })

  // A route names a URL the crawl must not follow. No path in the repository can confirm one, so
  // judging it here would report a finding about the wrong thing entirely.
  it('does not judge a route prefix, which no repository path can confirm', () => {
    const route: DeclaredExclusion = entry({
      setting: 'accessibilitySkipRoutes',
      pattern: '/media',
      kind: 'route',
    })
    expect(findUnreachedExclusions([route], MEASURED)).toEqual([])
  })

  // An entry with no reason is dropped rather than honoured, so it narrows nothing and the reason rule
  // above is the one that reports it. Reporting it twice would name one mistake as two.
  it('leaves an entry that states no reason to the rule that reports it', () => {
    const unstated: DeclaredExclusion = entry({ pattern: 'src/legacy/**', reason: '' })
    expect(findUnreachedExclusions([unstated], MEASURED)).toEqual([])
  })
})

// The accessibility sweep is a managed file, so these two settings are the whole of what a project may
// say about it. Both must fail closed: a malformed value leaves the crawl scanning more, never less.
describe('the accessibility sweep settings', () => {
  it('serves the crawl a default origin when the project declares none', () => {
    expect(readSettings({}).serverUrl).toBe('http://localhost:3000')
  })

  it('takes the origin a project declares, which ploaness cannot know', () => {
    const settings: Settings = readSettings({ ploaness: { serverUrl: 'http://localhost:4000' } })
    expect(settings.serverUrl).toBe('http://localhost:4000')
  })

  it('skips the Payload admin panel and REST API without being asked', () => {
    expect(readSettings({}).accessibilitySkipRoutes).toEqual(['/admin', '/api'])
  })

  it('adds a declared route prefix to the shipped ones rather than replacing them', () => {
    const routes: readonly string[] = readSettings({
      ploaness: {
        accessibilitySkipRoutes: [
          { pattern: '/preview', reason: 'requires an authenticated session' },
        ],
      },
    }).accessibilitySkipRoutes
    expect(routes).toContain('/preview')
    expect(routes).toContain('/admin')
  })

  it('cannot drop a shipped route prefix by declaring a narrower list', () => {
    const routes: readonly string[] = readSettings({
      ploaness: { accessibilitySkipRoutes: [{ pattern: '/preview', reason: 'authenticated' }] },
    }).accessibilitySkipRoutes
    expect(routes).toContain('/api')
  })

  it('does not honour a route prefix that states no reason', () => {
    const routes: readonly string[] = readSettings({
      ploaness: { accessibilitySkipRoutes: ['/preview'] },
    }).accessibilitySkipRoutes
    expect(routes).not.toContain('/preview')
  })

  it('records an unhonoured route prefix, so the wiring gate can report it', () => {
    const settings: Settings = readSettings({
      ploaness: { accessibilitySkipRoutes: ['/preview'] },
    })
    const settingNames: readonly string[] = settings.declaredExclusions.map(
      (found: DeclaredExclusion): string => found.setting,
    )
    expect(settingNames).toContain('accessibilitySkipRoutes')
  })
})

const declare = (value: unknown): Settings => readSettings({ ploaness: { coverageExclude: value } })

describe('reading declared exclusions', () => {
  it('honours an entry that states a role', () => {
    const settings: Settings = declare([
      { pattern: 'src/migrations/**', reason: 'generated migrations' },
    ])
    expect(settings.coverageExclude).toContain('src/migrations/**')
  })

  // Dropping it makes the gate stricter, which is the safe direction to fail in.
  it('does not honour an entry that states no reason', () => {
    const settings: Settings = declare([{ pattern: 'src/migrations/**' }])
    expect(settings.coverageExclude).not.toContain('src/migrations/**')
  })

  it('does not honour a bare string, which states no role at all', () => {
    expect(declare(['src/migrations/**']).coverageExclude).not.toContain('src/migrations/**')
  })

  it('still records an unhonoured entry, so a gate can report it', () => {
    const settings: Settings = declare(['src/migrations/**'])
    expect(settings.declaredExclusions.map((found: DeclaredExclusion) => found.pattern)).toContain(
      'src/migrations/**',
    )
  })

  it('names the setting an entry came from', () => {
    const settings: Settings = readSettings({
      ploaness: { typographyExclusions: [{ pattern: '^docs/', reason: 'vendored' }] },
    })
    expect(settings.declaredExclusions[0]?.setting).toBe('typographyExclusions')
  })

  it('keeps the shipped defaults whatever the project declares', () => {
    expect(declare([]).coverageExclude.length).toBeGreaterThan(0)
  })
})
