import { describe, expect, it } from 'vitest'
import {
  type DeclaredExclusion,
  findConvenienceExclusions,
  readSettings,
  type Settings,
} from '../src/settings.js'

const entry = (overrides: Partial<DeclaredExclusion> = {}): DeclaredExclusion => ({
  setting: 'coverageExclude',
  pattern: 'src/generated/**',
  reason: 'generated by the framework, so there is no hand-written logic to measure',
  ...overrides,
})

const isMissing = (): boolean => false
const isPresent = (): boolean => true

describe('findConvenienceExclusions', () => {
  it('accepts an exclusion that states the role it claims', () => {
    expect(findConvenienceExclusions([entry()], isMissing)).toEqual([])
  })

  it('reports an exclusion that states no reason', () => {
    const found: readonly string[] = findConvenienceExclusions([entry({ reason: '' })], isMissing)
    expect(found[0]).toContain('states no reason')
  })

  // The Coverage section forbids naming an individual file in as many words: a role is a category a
  // check can determine from a file, and one path is not a category.
  it('reports a pattern that names one existing file', () => {
    const single: DeclaredExclusion = entry({ pattern: 'src/lib/untested.ts' })
    expect(findConvenienceExclusions([single], isPresent)[0]).toContain('names one existing file')
  })

  it('accepts a glob, which describes a shape rather than one file', () => {
    expect(findConvenienceExclusions([entry({ pattern: 'src/**/*.tsx' })], isPresent)).toEqual([])
  })

  it('accepts a regular expression, which is likewise a shape', () => {
    const pattern: DeclaredExclusion = entry({ pattern: '^src/generated/' })
    expect(findConvenienceExclusions([pattern], isPresent)).toEqual([])
  })

  // A plain path that resolves to nothing is a stale entry, not a convenience; config-refs reports it.
  it('leaves a plain path that resolves to nothing alone', () => {
    expect(findConvenienceExclusions([entry({ pattern: 'src/gone.ts' })], isMissing)).toEqual([])
  })

  it('judges every entry, so one good exclusion cannot hide a bad one', () => {
    const entries: readonly DeclaredExclusion[] = [entry(), entry({ reason: '' })]
    expect(findConvenienceExclusions(entries, isMissing)).toHaveLength(1)
  })
})

const declare = (value: unknown): Settings => readSettings({ ploaness: { coverageExclude: value } })

describe('reading declared exclusions', () => {
  it('honours an entry that states a role', () => {
    const settings: Settings = declare([
      { pattern: 'src/migrations/**', reason: 'generated migrations' },
    ])
    expect(settings.coverageExclude).toContain('src/migrations/**')
  })

  // Dropping it makes the gate stricter, which is the safe direction to fail in.
  it('does not honour an entry that states no reason', () => {
    const settings: Settings = declare([{ pattern: 'src/migrations/**' }])
    expect(settings.coverageExclude).not.toContain('src/migrations/**')
  })

  it('does not honour a bare string, which states no role at all', () => {
    expect(declare(['src/migrations/**']).coverageExclude).not.toContain('src/migrations/**')
  })

  it('still records an unhonoured entry, so a gate can report it', () => {
    const settings: Settings = declare(['src/migrations/**'])
    expect(settings.declaredExclusions.map((found: DeclaredExclusion) => found.pattern)).toContain(
      'src/migrations/**',
    )
  })

  it('names the setting an entry came from', () => {
    const settings: Settings = readSettings({
      ploaness: { typographyExclusions: [{ pattern: '^docs/', reason: 'vendored' }] },
    })
    expect(settings.declaredExclusions[0]?.setting).toBe('typographyExclusions')
  })

  it('keeps the shipped defaults whatever the project declares', () => {
    expect(declare([]).coverageExclude.length).toBeGreaterThan(0)
  })
})
