// Binds this repository's own write denial to the set of files its build regenerates.
//
// ploaness denies an agent write access to every generated artefact of a governed project, and denied
// none of its own. Eleven files here are regenerated by a build: the seven `.asset` bodies copied from
// their root twins, and the four configs `packages/ploaness/build.ts` inlines. Editing one by hand
// produces a change the next build silently discards, which is the failure the denial exists to stop.
//
// The list is DERIVED from the manifest rather than restated in the settings file, so a managed path
// added to `manifest.tsv` fails here until the denial follows it. Restating it would leave two lists
// that must stay equal, and two lists that must stay equal will not.
//
// Both halves are derived now. The config half was restated - two names written out here beside four
// the build writes - and it drifted exactly as the paragraph above predicts: `biome-core.json` and
// `tsconfig-core.json` were generated, shipped, and denied to nobody, in this spec and in the settings
// file alike. It is read from the meta package's `files` now, which is the field that decides what the
// package ships and therefore cannot omit a config a consumer receives.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  asRecord,
  findDenialViolations,
  type PairedAsset,
  pairedAssets,
  parseManifest,
} from '@ploaness/governance'
import { describe, expect, it } from 'vitest'

const packageRoot: string = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const workspaceRoot: string = path.join(packageRoot, '..', '..')

// The configs `packages/ploaness/build.ts` inlines into the meta package, read from the manifest that
// ships them. `dist` is the only other entry of that field, and the hand-written `tsconfig.build.json`
// is deliberately absent from it, so filtering to the JSON entries names the generated four and nothing
// else. An empty answer throws rather than passing: a denial of nothing is trivially complete.
const inlinedConfigs = (): readonly string[] => {
  const manifest: Record<string, unknown> = asRecord(readJson('packages/ploaness/package.json'))
  const shipped: unknown = manifest['files']
  if (!Array.isArray(shipped)) {
    throw new TypeError('packages/ploaness/package.json declares no files list')
  }
  const configs: readonly string[] = shipped
    .filter(
      (entry: unknown): entry is string => typeof entry === 'string' && entry.endsWith('.json'),
    )
    .map((entry: string): string => `packages/ploaness/${entry}`)
  if (configs.length === 0) {
    throw new TypeError('packages/ploaness/package.json ships no generated config')
  }
  return configs
}

const readJson = (relativePath: string): unknown =>
  JSON.parse(readFileSync(path.join(workspaceRoot, relativePath), 'utf8'))

const generatedArtefacts = (): readonly string[] => {
  const manifestText: string = readFileSync(path.join(packageRoot, 'manifest.tsv'), 'utf8')
  const pairs: readonly PairedAsset[] = pairedAssets(parseManifest(manifestText).assets)
  return [
    ...pairs.map((pair: PairedAsset): string => `packages/assets/${pair.assetPath}`),
    ...inlinedConfigs(),
  ]
}

describe('the write denial this repository carries', () => {
  it('denies every artefact its own build regenerates', () => {
    const found: readonly string[] = findDenialViolations(
      readJson('.claude/settings.json'),
      undefined,
      generatedArtefacts(),
    )
    expect(found).toEqual([])
  })

  // Without this the assertion above would still pass if the manifest lost every pairing, because a
  // denial of nothing is trivially complete.
  it('has a generated set to deny in the first place', () => {
    expect(generatedArtefacts().length).toBeGreaterThan(inlinedConfigs().length)
  })

  // The regression this file was repaired for. The two core halves are generated by the same build and
  // shipped by the same manifest as the two the list used to stop at, and naming them is what says the
  // derivation reaches the whole set rather than the half somebody remembered.
  it('counts the core halves among the configs the build regenerates', () => {
    expect(inlinedConfigs()).toStrictEqual([
      'packages/ploaness/biome.json',
      'packages/ploaness/tsconfig.json',
      'packages/ploaness/biome-core.json',
      'packages/ploaness/tsconfig-core.json',
    ])
  })
})
