// Binds this repository's own write denial to the set of files its build regenerates.
//
// ploaness denies an agent write access to every generated artefact of a governed project, and denied
// none of its own. Nine files here are regenerated by a build: the seven `.asset` bodies copied from
// their root twins, and the two configs `packages/ploaness/build.mjs` inlines. Editing one by hand
// produces a change the next build silently discards, which is the failure the denial exists to stop.
//
// The list is DERIVED from the manifest rather than restated in the settings file, so a managed path
// added to `manifest.tsv` fails here until the denial follows it. Restating it would leave two lists
// that must stay equal, and two lists that must stay equal will not.
import { readFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  findDenialViolations,
  type PairedAsset,
  pairedAssets,
  parseManifest,
} from '@ploaness/governance'
import { describe, expect, it } from 'vitest'

const packageRoot: string = path.join(path.dirname(fileURLToPath(import.meta.url)), '..')
const workspaceRoot: string = path.join(packageRoot, '..', '..')

// Generated by `packages/ploaness/build.mjs`, which inlines the shipped configs into the meta package.
const INLINED_CONFIGS: readonly string[] = [
  'packages/ploaness/biome.json',
  'packages/ploaness/tsconfig.json',
]

const readJson = (relativePath: string): unknown =>
  JSON.parse(readFileSync(path.join(workspaceRoot, relativePath), 'utf8'))

const generatedArtefacts = (): readonly string[] => {
  const manifestText: string = readFileSync(path.join(packageRoot, 'manifest.tsv'), 'utf8')
  const pairs: readonly PairedAsset[] = pairedAssets(parseManifest(manifestText).assets)
  return [
    ...pairs.map((pair: PairedAsset): string => `packages/assets/${pair.assetPath}`),
    ...INLINED_CONFIGS,
  ]
}

describe('the write denial this repository carries', () => {
  it('denies every artefact its own build regenerates', () => {
    const found: readonly string[] = findDenialViolations(
      readJson('.claude/settings.json'),
      undefined,
      generatedArtefacts(),
    )
    expect(found).toEqual([])
  })

  // Without this the assertion above would still pass if the manifest lost every pairing, because a
  // denial of nothing is trivially complete.
  it('has a generated set to deny in the first place', () => {
    expect(generatedArtefacts().length).toBeGreaterThan(INLINED_CONFIGS.length)
  })
})
